[versions]
morphe-patcher = "1.8.0"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
morphe-patches-library = "1.6.0-dev.2"
annotation = "1.10.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
morphe-extensions-library = { module = "app.morphe:morphe-extensions-library", version.ref = "morphe-patches-library" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
